site_name: Google Cloud Notes
site_url: https://cloud.danielfrg.com
site_author: Daniel Rodriguez
site_description: >-
  Notes on how I do stuff in Google Cloud
# repo_url: https://github.com/danielfrg/cloud.danielfrg.com
copyright: Copyright &copy; 2023 Daniel Rodriguez
site_dir: dist

nav:
  - Terraform:
      - Terraform: terraform/index.md
      - GitHub Actions with Identity Pools: terraform/ipd-github-actions.md
      - Public GCS Bucket: terraform/gcs-public-bucket.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        name: Switch to light mode
        icon: material/brightness-7
    # Palette toggle for dark mode
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        name: Switch to dark mode
        icon: material/brightness-3

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search

extra:
  analytics:
    provider: google
    property: G-3673QMK9C4
